// <auto-generated />
using System;
using JetlagBot.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JetlagBot.App.Data.Migrations
{
    [DbContext(typeof(JetlagBotDbContext))]
    [Migration("20260630092232_AddVouchChannelId")]
    partial class AddVouchChannelId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JetlagBot.App.Data.Entities.AdminUser", b =>
                {
                    b.Property<string>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AddedByDiscordUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("DiscordUserId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("JetlagBot.App.Data.Entities.GuildSettings", b =>
                {
                    b.Property<string>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("MinimumMembershipAgeDays")
                        .HasColumnType("integer");

                    b.Property<string>("VouchChannelId")
                        .HasColumnType("text");

                    b.Property<int>("VouchCooldownDays")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("JetlagBot.App.Data.Entities.Vouch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TargetDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoucherDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VoucherUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "TargetUserId");

                    b.HasIndex("GuildId", "VoucherUserId", "CreatedAtUtc");

                    b.ToTable("Vouches");
                });
#pragma warning restore 612, 618
        }
    }
}
